version: '3.7'
services:
  api-proxy:
    container_name: api-proxy
    image: nginx:latest
    volumes:
      - '/etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro'
    restart: always
    ports:
      - '16443:6443' # 6443:6443
    networks:
      netgroup:
        ipv4_address: 172.18.0.49

networks:
  netgroup:
    name: netgroup
    driver: bridge
    attachable: true
    ipam:
      config:
        - subnet: 172.18.0.0/16
          gateway: 172.18.0.1
