apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2022-05-06T14:36:20Z"
  generateName: nginx-5578584966-
  labels:
    app: web
    pod-template-hash: "5578584966"
    run: nginx
  name: nginx-5578584966-psd2r
  namespace: default
  ownerReferences:
  - apiVersion: apps/v1
    blockOwnerDeletion: true
    controller: true
    kind: ReplicaSet
    name: nginx-5578584966
    uid: 3fef4c14-f81d-4692-acdf-6c57ec68948e
  resourceVersion: "2188"
  selfLink: /api/v1/namespaces/default/pods/nginx-5578584966-psd2r
  uid: 6608fe99-b8e8-4c35-a943-6b77c65ea234
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: nginx
    ports:
    - containerPort: 80
      protocol: TCP
    resources: {}
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      name: default-token-572m4
      readOnly: true
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  nodeName: ubuntu
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - name: default-token-572m4
    secret:
      defaultMode: 420
      secretName: default-token-572m4
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-05-06T14:36:20Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2022-05-06T14:36:36Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2022-05-06T14:36:36Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2022-05-06T14:36:20Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://57af8d90b0d919280c7b3982c30cb8346f7948b5159b9dd47d56bc8274f790cf
    image: nginx:latest
    imageID: docker-pullable://nginx@sha256:859ab6768a6f26a79bc42b231664111317d095a4f04e4b6fe79ce37b3d199097
    lastState: {}
    name: nginx
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2022-05-06T14:36:34Z"
  hostIP: 192.168.54.139
  phase: Running
  podIP: 10.217.0.181
  podIPs:
  - ip: 10.217.0.181
  qosClass: BestEffort
  startTime: "2022-05-06T14:36:20Z"
