apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-proxy
  name: api-proxy
spec:
  ports:
    - name: http
      port: 6443
      targetPort: 6443
  selector:
    app: api-proxy
status:
  loadBalancer: {}
---