apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api-proxy
  name: api-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-proxy
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: api-proxy
    spec:
      containers:
        - image: nginx:latest
          name: api-proxy
          ports:
            - containerPort: 6443
          resources: {}
          volumeMounts:
            - mountPath: /etc/nginx/nginx.conf
              name: api-proxy-claim0
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: api-proxy-claim0
          persistentVolumeClaim:
            claimName: api-proxy-claim0
            readOnly: true
status: {}
---